build:
    test:
        image: dockerdist.bdmd.com/cloudbase:latest
        pull: true
        commands:
            - wget http://openlight-buildrepo.bdmd.com/v1/build/buildscript -O olbuilder.py && python olbuilder.py test
    build:
        image: dockerdist.bdmd.com/cloudbase:latest
        pull: true
        commands:
            - wget http://openlight-buildrepo.bdmd.com/v1/build/buildscript -O olbuilder.py && python olbuilder.py build
        when:
            event: push
            repo: lipixun/pyunified-rpc 
deploy:
    rsync:
        user: ol_pyunifiedrpc
        host: openlight-buildrepo.bdmd.com
        port: 2222
        source: ol_*
        target: ~/$$BUILD_NUMBER
        delete: true
        recursive: true
        when:
            event: push
            repo: lipixun/pyunified-rpc
notify:
    webhook:
        method: POST
        urls:
            - http://openlight-buildrepo.bdmd.com/v1/build/drone/hook
        content_type: application/json
        when:
            event: push
            repo: lipixun/pyunified-rpc
