build:
    test:
        image: dockerdist.bdmd.com/cloudbase:latest
        commands:
            - ./test.sh
    build:
        image: dockerdist.bdmd.com/cloudbase:latest
        commands:
            - ./build.sh
        when:
            event: push
            repo: lipixun/pyunified-rpc 
deploy:
    rsync:
        user: ol_unifiedrpc
        host: openlight-buildrepo.bdmd.com
        port: 2222
        source: dist/
        target: ~/$$COMMIT
        delete: true
        recursive: true
        when:
            event: push
            repo: lipixun/pyunified-rpc
notify:
    webhook:
        method: POST
        urls:
            - http://openlight-api.bdmd.com/v1/build/hook
        headers:
            X-Project-ID: unifiedrpc
        when:
            success: true
            event: push
            repo: lipixun/pyunified-rpc
